
RegisterCommand('911', function(source, args)
    local msg = table.concat(args, ' ')
    local caller = GetPlayerName(PlayerPedId())
    Alert('~g~[SUCCESS] ~w~Police Alerted')
    local coord = NetworkGetPlayerCoords(caller)
    if IsPedInAnyPoliceVehicle(-1) then
        Wait(5000)
        Alert('~r~[9-1-1:~o~'..caller..'~r~] ~w~'..msg)
        -- Creat the Blip
        local callBlip = AddBlipForCoord(coord.x, coord.y, coord.z)
        SetBlipSprite(callBlip, Config.BlipSprite)
        SetBlipColour(callBlip, Config.BlipColor)
        SetBlipDisplay(callBlip, 2)
        SetBlipAsShortRange(callBlip, true)
        AddTextEntry('CALLBLIP', '9-1-1 call generated by '..caller)
        BeginTextCommandSetBlipName('CALLBLIP')
        EndTextCommandSetBlipName(callBlip)
        Wait(60000)
        SetBlipSprite(callBlip, 2) -- this makes the blip disapear
    end
end, false)

RegisterCommand('delveh', function()
    local veh = GetVehiclePedIsIn(PlayerPedId(), false)
    DeleteVehicle(veh)
end, false)

-- Notification Fucntion
function Alert(msg)
    SetNotificationTextEntry('STRING')
    AddTextComponentString(msg)
    DrawNotification(true, false)
end